name: scan_job
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  animations: ^2.1.1
  bloc: ^9.2.0
  equatable: ^2.0.8
  flex_color_scheme: ^8.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.7+1
  go_router: ^15.1.2
  google_fonts: ^8.0.2
  intl: ^0.20.2
  markdown: ^7.3.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_web_auth_2: ^5.0.1

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  langchain: any
  langchain_openai: any
  mocktail: ^1.0.4
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true
  generate: true
